Repository energywebfoundation/zero, pull requests merged in 2021-09, with the labels that each got.

#39 chore: update Nx to v12.8
  apps/ui-core-e2e/src/plugins/index.js
  jest.config.js
  libs/ui/core/.storybook/tsconfig.json
  migrations.json
  package.json
  yarn.lock
Labels: chore

#40 fix: fix type problems
  libs/ui/core/src/lib/components/facility-document-item/facility-document-item.tsx
  libs/ui/core/src/lib/components/green-label-list/green-label-list.tsx
  libs/ui/core/src/lib/containers/generic-form-container/generic-form-container.effects.tsx
Labels: bug, bugfix

#41 feat: implemented 404 page & loading page
  apps/zero/src/app/app.effects.ts
  apps/zero/src/app/app.tsx
  apps/zero/src/index.html
  apps/zero/src/main.tsx
  apps/zero/src/pages/page-not-found/page-not-found-page.tsx
  apps/zero/src/pages/page-not-found/page-not-found.spec.tsx
  apps/zero/src/styles.scss
  libs/buyer/src/pages/buyer-landing-page/buyer-landing-page.tsx
  libs/localization/src/translations/en.json
  libs/seller/src/pages/seller-landing-page/seller-landing-page.tsx
  libs/store/configure/src/features/appState/appState.epics.ts
  libs/store/configure/src/features/appState/appState.slice.ts
  libs/store/configure/src/features/authState/authState.epics.ts
  libs/store/configure/src/features/authState/authState.slice.ts
  libs/ui/account/src/containers/index.ts
  libs/ui/account/src/containers/top-nav-bar-container/top-nav-bar-container.effects.ts
  libs/ui/account/src/containers/top-nav-bar-container/top-nav-bar-container.spec.tsx
  libs/ui/account/src/containers/top-nav-bar-container/top-nav-bar-container.tsx
  libs/ui/account/src/index.ts
  libs/ui/account/src/lib/ui-account.tsx
  libs/ui/account/src/pages/account-page/account-page.tsx
  libs/ui/auth/src/pages/auth-page/auth-page.tsx
  libs/ui/core/src/index.ts
  libs/ui/core/src/lib/layouts/layout-no-topbar/layout-no-topbar.spec.tsx
  libs/ui/core/src/lib/layouts/layout-no-topbar/layout-no-topbar.tsx
  libs/ui/core/src/lib/layouts/layout-with-topbar/layout-with-topbar-container.tsx
  libs/ui/core/src/lib/layouts/layout-with-topbar/layout-with-topbar.effects.ts
  libs/ui/core/src/lib/layouts/layout-with-topbar/layout-with-topbar.spec.tsx
  libs/ui/core/src/lib/pages/index.ts
  libs/ui/core/src/lib/pages/loading-page/loading-page.tsx
  libs/ui/core/src/lib/pages/loading-page/loading.spec.tsx
  libs/ui/core/src/lib/pages/loading-page/windmill.svg
  libs/ui/core/src/lib/pages/not-found-page/not-found-page.spec.tsx
  libs/ui/core/src/lib/pages/not-found-page/not-found-page.tsx
  libs/ui/core/src/lib/pages/not-found-page/not_found.svg
  libs/zero-ui-assets/src/lib/svg/logo.svg
  package.json
  yarn.lock
Labels: frontend

#43 feat(notifications): implemented notification system
  apps/zero/src/app/app.effects.ts
  apps/zero/src/app/app.tsx
  apps/zero/src/main.tsx
  libs/store/configure/src/Providers/StoreProvider.tsx
  libs/store/configure/src/features/index.ts
  libs/store/configure/src/features/notificationState/index.ts
  libs/store/configure/src/features/notificationState/notificationState.epics.ts
  libs/store/configure/src/features/notificationState/notificationState.slice.ts
  libs/ui/core/src/index.ts
  libs/ui/core/src/lib/components/notification-item/notification-item.spec.tsx
  libs/ui/core/src/lib/components/notification-item/notification-item.tsx
  libs/ui/core/src/lib/components/top-nav-bar/top-nav-bar.tsx
  libs/ui/core/src/lib/containers/notification-area-container/notification-area-container.effects.ts
  libs/ui/core/src/lib/containers/notification-area-container/notification-area-container.tsx
  libs/ui/core/src/lib/pages/index.ts
  libs/ui/core/src/lib/pages/loading-page/loading-page.tsx
  libs/ui/theme/src/lib/config/themeConfig.ts
  package.json
  yarn.lock
Labels: frontend

#44 feat: integrated with S3 storage
  .env.example
  apps/zero-api/prisma/migrations/20210909093531_initial/migration.sql
  apps/zero-api/prisma/schema.prisma
  apps/zero-api/src/app/app.module.ts
  apps/zero-api/src/files/dto/file-metadata.dto.ts
  apps/zero-api/src/files/files.controller.spec.ts
  apps/zero-api/src/files/files.controller.ts
  apps/zero-api/src/files/files.service.spec.ts
  apps/zero-api/src/files/files.service.ts
  apps/zero-api/src/users/users-files.controller.spec.ts
  apps/zero-api/src/users/users-own-files.controller.spec.ts
  apps/zero-api/swagger.json
  package.json
  yarn.lock
Labels: backend

#49 feat(forms): implement generic map field
  libs/seller/src/components/seller-add-facilities-location-form/seller-add-facilities-location-form-fields.ts
  libs/seller/src/components/seller-add-facilities-location-form/seller-add-facilities-location-form.tsx
  libs/ui/core/src/lib/components/form/form-field-file-list/form-field-file-list.spec.tsx
  libs/ui/core/src/lib/components/form/form-field-green-label-list/form-field-green-label-list.spec.tsx
  libs/ui/core/src/lib/components/form/form-field-green-label-list/form-field-green-label-list.test.tsx
  libs/ui/core/src/lib/components/form/form-field-map/form-field-map.spec.tsx
  libs/ui/core/src/lib/components/form/form-field-map/form-field-map.stories.tsx
  libs/ui/core/src/lib/components/form/form-field-map/form-field-map.tsx
  libs/ui/core/src/lib/components/form/form-field-map/index.ts
  libs/ui/core/src/lib/components/generic-map/generic-map.spec.tsx
  libs/ui/core/src/lib/components/generic-map/generic-map.tsx
  libs/ui/core/src/lib/containers/generic-form-container/generic-form-container.effects.tsx
  libs/ui/core/src/lib/containers/generic-form-container/generic-form-container.tsx
  libs/ui/core/src/lib/containers/generic-form-field-container/generic-form-field-container.spec.tsx
  libs/ui/core/src/lib/containers/generic-form-field-container/generic-form-field-container.tsx
Labels: frontend

#62 chore: upgraded Prisma to v3
  apps/zero-api/Dockerfile
  apps/zero-api/src/prisma/prisma.service.ts
  package.json
  yarn.lock
Labels: chore, backend
